#! /usr/bin/env bash

test: test.c Array.c Array.h String.c String.h Object.c Object.h ../j2ctools.c ../headers.h
	gcc test.c Array.c Array.h String.c String.h Object.c Object.h ../j2ctools.c ../headers.h -o t 
	

